server:
  port: 8082

spring:
  redis:
    database: 0
    host: 192.168.0.107
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1m
        max-idle: 10
        min-idle: 0
    timeout: 1000m

